# Matrices
## Linear Algebra Foundations

This notebook covers:
- Matrix representation
- Matrix transpose
- Matrix multiplication
- Identity matrix
- NumPy implementation


$$A = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}$$

Transposing is swapping rows and columns

$$A = \begin{bmatrix} 1 & 3 \\ 2 & 4 \end{bmatrix}$$

Multiplication is dot product of row and column

Identity matrix

A * I = A

$$I = \begin{bmatrix} 1 & 0 \\ 0 & 1 \end{bmatrix}$$

In [ ]:
from re import I
import numpy as np

m = np.array([[1, 2], [3, 4]])
transpose = m.T

print(m)
print(transpose)

c = m @ m

print(c)

identity = np.eye(2)
print(identity)
print(c @ identity)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[[ 7 10]
 [15 22]]
[[1. 0.]
 [0. 1.]]
[[ 7. 10.]
 [15. 22.]]
